### ISSUE TITLE
iOS Unified Support

### ISSUE THREAD

**Issue by saad-salahuddin-confiz** [Readify/AdalXamarinIos#5]
Will you be converting this to support x64 (Xamarin Unified)? And is there an ETA for the release?

"Starting February 1, 2015, new iOS apps uploaded to the App Store must include 64-bit support and be built with the iOS 8 SDK, included in Xcode 6 or later. To enable 64-bit in your project, we recommend using the default Xcode build setting of “Standard architectures” to build a single binary with both 32-bit and 64-bit code." [https://developer.apple.com/news/?id=10202014a]

**Comment by tathamoddie** [comment]
@graemechristie ?

I roughly remember that we maybe didn't even need this library at all any more.

**Comment by graemechristie** [comment]
Microsoft announced back in October that ADAL .NET v3 will support Xamarin out of the box. This pretty much obsoletes this library. The preview for v3 is available on nuget here:

https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/3.0.110281957-alpha

More info here:

http://www.cloudidentity.com/blog/2014/10/30/adal-net-v3-preview-pcl-xamarin-support/

and here:

http://blogs.technet.com/b/ad/archive/2014/10/30/azure-ad-adal-net-v3-libraries-with-xamarin-support-now-in-preview.aspx

I'll add a note to the readme.md, directing people to these resources.

**Comment by saad-salahuddin-confiz** [comment]
Thanks
